"""try 6

Revision ID: 0b619b9f45b2
Revises: a677b04e7b4b
Create Date: 2023-05-10 15:27:23.831224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b619b9f45b2'
down_revision = 'a677b04e7b4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
