"""try 7

Revision ID: 0d235043519a
Revises: 0b619b9f45b2
Create Date: 2023-05-10 15:29:04.174802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d235043519a'
down_revision = '0b619b9f45b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
