"""db couriers creation

Revision ID: 20046a95ce63
Revises: 
Create Date: 2023-05-09 13:54:37.463929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20046a95ce63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('courier_type', sa.String(), nullable=False),
    sa.Column('regions', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('working_hours', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('courier_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('couriers')
    # ### end Alembic commands ###
