"""db orders&couriers creations

Revision ID: 28ad31612243
Revises: ddd3905bd660
Create Date: 2023-05-09 15:09:47.000246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28ad31612243'
down_revision = 'ddd3905bd660'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('couriers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('courier_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('courier_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('regions', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
    sa.Column('working_hours', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('courier_id', name='couriers_pkey')
    )
    # ### end Alembic commands ###
