"""try 3

Revision ID: 3433d75aae28
Revises: 779ab23e7b0d
Create Date: 2023-05-09 22:57:27.605521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3433d75aae28'
down_revision = '779ab23e7b0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
