"""try 4

Revision ID: 4cff10b3bfa5
Revises: 3433d75aae28
Create Date: 2023-05-09 23:03:50.134175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cff10b3bfa5'
down_revision = '3433d75aae28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('courier_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'courier_id')
    # ### end Alembic commands ###
