"""try 2

Revision ID: 779ab23e7b0d
Revises: ebe4ea854596
Create Date: 2023-05-09 20:01:30.860526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779ab23e7b0d'
down_revision = 'ebe4ea854596'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('costs', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('completed_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'completed_time')
    op.drop_column('orders', 'costs')
    # ### end Alembic commands ###
