"""try 5

Revision ID: a677b04e7b4b
Revises: 4cff10b3bfa5
Create Date: 2023-05-10 14:29:50.658206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a677b04e7b4b'
down_revision = '4cff10b3bfa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
