"""db couriers creations

Revision ID: ae1d89132a71
Revises: 20046a95ce63
Create Date: 2023-05-09 14:07:55.024687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1d89132a71'
down_revision = '20046a95ce63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
