"""db orders creations

Revision ID: ddd3905bd660
Revises: ae1d89132a71
Create Date: 2023-05-09 14:52:41.949193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd3905bd660'
down_revision = 'ae1d89132a71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
