"""db orders&couriers

Revision ID: e98bb507340c
Revises: 28ad31612243
Create Date: 2023-05-09 15:24:10.276651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98bb507340c'
down_revision = '28ad31612243'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
