"""try 1

Revision ID: ebe4ea854596
Revises: e98bb507340c
Create Date: 2023-05-09 16:02:42.036357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe4ea854596'
down_revision = 'e98bb507340c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('courier_type', sa.String(), nullable=False),
    sa.Column('regions', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('working_hours', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('courier_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.String(), nullable=False),
    sa.Column('regions', sa.Integer(), nullable=False),
    sa.Column('delivery_hours', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('couriers')
    # ### end Alembic commands ###
